# --- !Ups

CREATE TABLE User (
  userid    INT GENERATED BY DEFAULT AS IDENTITY,
  username VARCHAR(255)  NOT NULL,
  password VARCHAR(255) NOT NULL ,
  firstname VARCHAR(255) NOT NULL,
  lastname  VARCHAR(255) NOT NULL,
  email     VARCHAR(255) NOT NULL,
  nickname  VARCHAR(255),
  lastlogin TIMESTAMP ,
  picture   BLOB ,
  PRIMARY KEY (userid)
);
CREATE TABLE Chat (
  chatid INT GENERATED BY DEFAULT AS IDENTITY,
  chatname   VARCHAR(255) NOT NULL,
  PRIMARY KEY (chatid)
);

CREATE TABLE UsertoChat (
  chatid INT          NOT NULL,
  userid INT          NOT NULL,
);

CREATE TABLE Timelineentry (
  Timelineid INT GENERATED BY DEFAULT AS IDENTITY,
  userid     INT          NOT NULL,
  deadtime   TIMESTAMP    NOT NULL,
  message    VARCHAR(255) NOT NULL,
  PRIMARY KEY (Timelineid)
);
CREATE TABLE History (
  messageid   INT GENERATED BY DEFAULT AS IDENTITY,
  chatid      INT       NOT NULL,
  userid      INT       NOT NULL,
  messagetime TIMESTAMP NOT NULL,
  PRIMARY KEY (messageid)
);
CREATE TABLE Friendrequest (
  requestfrom INT NOT NULL,
  requestto   INT NOT NULL
);
CREATE TABLE GuiSettings (
  userid     INT             NOT NULL,
  optionmenu BIT DEFAULT '1' NOT NULL,
  timeline   BIT DEFAULT '1' NOT NULL,
  lastchat   INT             NOT NULL
);
ALTER TABLE Friendrequest
  ADD CONSTRAINT FKFriendrequ359114 FOREIGN KEY (requestfrom) REFERENCES User (userid);
ALTER TABLE Friendrequest
  ADD CONSTRAINT FKFriendrequ51650 FOREIGN KEY (requestto) REFERENCES User (userid);
ALTER TABLE Timelineentry
  ADD CONSTRAINT FKTimelineen399460 FOREIGN KEY (userid) REFERENCES User (userid);
ALTER TABLE History
  ADD CONSTRAINT FKHistory174533 FOREIGN KEY (userid) REFERENCES User (userid);
ALTER TABLE History
  ADD CONSTRAINT FKHistory574831 FOREIGN KEY (chatid) REFERENCES Chat (chatid);
ALTER TABLE GuiSettings
  ADD CONSTRAINT FKGuiSetting68533 FOREIGN KEY (userid) REFERENCES User (userid);
ALTER TABLE GuiSettings
  ADD CONSTRAINT FKGuiSetting816374 FOREIGN KEY (lastchat) REFERENCES Chat (chatid);
ALTER TABLE UsertoChat
  ADD CONSTRAINT FKUsertoChat816374 FOREIGN KEY (chatid) REFERENCES Chat (chatid);
ALTER TABLE UsertoChat
  ADD CONSTRAINT FKUsertoChat816378 FOREIGN KEY (userid) REFERENCES User (userid);

# --- !Downs

DROP TABLE User;
DROP TABLE Chat;
DROP TABLE Timelineentry;
DROP TABLE History;
DROP TABLE Friendrequest;
DROP TABLE GuiSettings;
DROP TABLE UsertoChat;